ln -sf ~/dotfiles/.vimrc         ~/.vimrc
ln -sf ~/dotfiles/.inputrc       ~/.inputrc
ln -sf ~/dotfiles/.bashrc        ~/.bashrc
ln -sf ~/dotfiles/.xmonad        ~/.xmonad
ln -sf ~/dotfiles/.stalonetrayrc ~/.stalonetrayrc
ln -sf ~/dotfiles/lighter.sh     ~/lighter.sh
ln -sf ~/dotfiles/darker.sh      ~/darker.sh
ln -sf ~/dotfiles/.xinitrc       ~/.xinitrc
ln -sf ~/dotfiles/.Xresources    ~/.Xresources
ln -sf ~/dotfiles/.vifm          ~/.vifm
